# Generated by Django 5.1.4 on 2025-01-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='live_in',
            field=models.CharField(blank=True, choices=[('Taipei', '臺北市'), ('NewTaipei', '新北市'), ('Keelung', '基隆市'), ('Taoyuan', '桃園市'), ('Hsinchu_City', '新竹市'), ('Hsinchu', '新竹縣'), ('Miaoli', '苗栗縣'), ('Taichung', '臺中市'), ('Changhua', '彰化縣'), ('Nantou', '南投縣'), ('Yunlin', '雲林縣'), ('Chiayi_City', '嘉義市'), ('Chiayi', '嘉義縣'), ('Tainan', '臺南市'), ('Kaohsiung', '高雄市'), ('Pingtung', '屏東縣'), ('Yilan', '宜蘭縣'), ('Hualien', '花蓮縣'), ('Taitung', '臺東縣'), ('Penghu', '澎湖縣'), ('Kinmen', '金門縣'), ('Lienchiang', '連江縣')], max_length=100, null=True, verbose_name='居住地'),
        ),
    ]
