# Generated by Django 5.1.4 on 2025-01-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_password_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='介紹一下你自己', null=True, verbose_name='自我介紹'),
        ),
    ]
