# Generated by Django 5.1.4 on 2024-12-16 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='活動標題', max_length=100)),
                ('description', models.TextField(blank=True, help_text='活動描述')),
                ('address', models.CharField(help_text='活動地址，例：台北市信義區市府路1號', max_length=255)),
                ('start_time', models.DateTimeField(help_text='活動開始時間')),
                ('end_time', models.DateTimeField(blank=True, help_text='活動結束時間(選填)', null=True)),
                ('max_participants', models.PositiveIntegerField(default=10, help_text='參加人數上限')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='活動建立時間')),
                ('creator', models.ForeignKey(help_text='活動創辦人', on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
