# Generated by Django 5.1.4 on 2025-01-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='活動標題', max_length=15)),
                ('description', models.TextField(blank=True, help_text='活動描述')),
                ('address', models.CharField(help_text='活動地址，例：台北市信義區市府路1號', max_length=255)),
                ('start_time', models.DateTimeField(help_text='活動開始時間')),
                ('duration', models.PositiveIntegerField(default=1, help_text='預估活動持續時間（小時）')),
                ('max_participants', models.PositiveIntegerField(default=10, help_text='參加人數上限')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='活動建立時間')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分類名稱', max_length=15)),
                ('description', models.TextField(blank=True, help_text='分類描述', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='排序')),
            ],
        ),
        migrations.CreateModel(
            name='MeetupPaticipat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='加入時間')),
            ],
        ),
    ]
