# Generated by Django 5.1.4 on 2024-12-22 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分類名稱', max_length=15)),
                ('description', models.TextField(blank=True, help_text='分類描述', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='排序')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='end_time',
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='預估活動持續時間（小時）'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(help_text='活動標題', max_length=15),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, help_text='活動分類', null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.category'),
        ),
    ]
