# Generated by Django 5.1.4 on 2025-01-07 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分類名稱', max_length=15)),
                ('description', models.TextField(blank=True, help_text='分類描述', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='排序')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='end_time',
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='預估聚會持續時間（小時）'),
        ),
        migrations.AddField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(default=1, help_text='聚會建立者', on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='activities_photo'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(help_text='聚會標題', max_length=15),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, help_text='聚會分類', null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.category'),
        ),
        migrations.CreateModel(
            name='MeetupPaticipat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='加入時間')),
                ('activity', models.ForeignKey(help_text='聚會', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='activities.activity')),
                ('participant', models.ForeignKey(help_text='參與者', on_delete=django.db.models.deletion.CASCADE, related_name='meetups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('activity', 'participant')},
            },
        ),
    ]
