# Generated by Django 5.1.4 on 2025-01-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='activities_photo'),
        ),
    ]
