# Generated by Django 5.1.4 on 2025-01-13 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='活動是否已審核通過'),
        ),
        migrations.AddField(
            model_name='activity',
            name='rejection_reason',
            field=models.CharField(blank=True, help_text='活動拒絕原因', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('pending', '待審核'), ('approved', '已通過'), ('rejected', '已拒絕'), ('expired', '已過期')], default='pending', help_text='聚會狀態', max_length=10),
        ),
        migrations.CreateModel(
            name='ActivityApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False, help_text='是否審核通過')),
                ('comment', models.TextField(blank=True, help_text='審核意見', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='審核時間')),
                ('activity', models.ForeignKey(help_text='被審核的活動', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='activities.activity')),
                ('reviewer', models.ForeignKey(help_text='審核者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
