# Generated by Django 5.1.4 on 2025-01-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflows', '0002_payment_rename_wallets_wallet_delete_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(verbose_name='交易金額'),
        ),
    ]
