# Generated by Django 5.1.4 on 2025-01-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflows', '0004_wallet_balence_wallet_created_at_wallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balence',
            field=models.IntegerField(default=0, verbose_name='餘額'),
        ),
    ]
