# Generated by Django 5.1.4 on 2025-01-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflows', '0005_alter_wallet_balence'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='create_activity',
            field=models.IntegerField(default=0, verbose_name='創建活動'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='join_activity',
            field=models.IntegerField(default=0, verbose_name='參加活動'),
        ),
    ]
